# action.yml
name: 'VRLabs Unity Exporter'
description: 'Uses Unity Package Exporter by Lachee to export a .unitypackage file from a Unity Project. Updated by VRLabs'
inputs:
  unityProjectPath:
    description: 'Path to the unity project'
    required: true
    default: './'
  outputPackagePath:
    description: 'Path to the output package'
    required: false
    default: './artifacts/output.unitypackage'
outputs:
  artifactsPath:
    description: 'Path to the output package'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.unityProjectPath }}
    - ${{ inputs.outputPackagePath }}
